### PR TITLE
Add janet impl

### PR DESCRIPTION
**Pull request by monarrk**
An implementation of the question function in the [Janet programming language](https://janet-lang.org). The current impl is a tad buggy, but it works for the most part.

### CODE REVIEW

**Review by superwhiskers — CHANGES_REQUESTED** [review]
no conformance to the style of the existing impl

**Comment by monarrk** [comment]
Conforming to current impls is difficult due to Janet's lack of returns. This is just a backwards way of doing the same thing; checking to see if the answer is *not* in the list and then recurse if that's the case. I don't think that it is possible to fully conform to the current impl at all, but even if you were able to it would be really hacky and unreadable.

**Comment by superwhiskers** [comment]
am rewriting it. keep in mind that the conformance wasn't about what you think it was, though

**Comment by superwhiskers** [comment]
no longer needed. i wrote one which does things in a more efficient way. also, the nonconformance was about how you didn't use the same `question("foo", ["bar", "baz"])` or `(question "foo" ["bar" "baz"])` that most use

**Pull request closed without merging**
